### PR TITLE
NEW: add MiniBase Chime (T8023)

### PR DESCRIPTION
**Pull request by martijnpoppen**
New chime device
 Delivered together with E340 Doorbell.
Everything is tested and working 

I can share the device with you

### CODE REVIEW

**Comment by bropat** [comment]
Todo:

- [ ] Add entry for device in docs/supported_devices.md
- [ ] Add images for device under docs/_media

**Comment by bropat** [comment]
@martijnpoppen 

Can you tell me the tested firmware version of the MiniBase Chime?

**Comment by martijnpoppen** [comment]
Will do tomorrow @bropat

**Comment by martijnpoppen** [comment]
@bropat sorry I thought I shared already 🤦🏼 

Shared it now (as resident).
firmware 3.3.1.5m_0.5

PS: Did you already removed access to my other shared devices? :)

**Comment by bropat** [comment]
@martijnpoppen 

Thank you very much, but unfortunately I see the minibase offline at the moment. Could you put it online?

> PS: Did you already removed access to my other shared devices? :)

Yes, already removed back then.

**Comment by bropat** [comment]
@martijnpoppen 

I removed the sharing. Thanks!

**Pull request merged**
