### PR TITLE
Send an event when the alarm is armed and alarm events from p2p

### PR DESCRIPTION
**Pull request by Palmke**
Emit an event when the alarm has been armed. This logic applies initially to the HB2, but I assume it applies to other systems as well.
This is when the leave delay (time to leave the house) has expired. Another case where this applies is when the alarm has been activated and the user cancels the alarm in the app. This is achieved by tapping that wonky red floating button.

### CODE REVIEW

**Comment by Palmke** [comment]
@bropat so I've rewired `alarm event` to use `CMD_SET_TONE_FILE`.
Can you verify for me in the app code that alarm events `HUB_STOP` and `DEV_STOP` aren't used in the notifications?

**Comment by bropat** [comment]
@Palmke 

This events are constants that are lost during decompiling...
Finding the exact source code lines takes a lot of time that I don't have at the moment. I'm sorry.

**Comment by Palmke** [comment]
Alright so how do you want to approach this? `HUB_STOP` is 100% a signal that the alarm is armed for the HB2.
I can change it so that it also forwards `HUB_STOP` and `DEV_STOP` along with an `alarm armed` event.

**Comment by bropat** [comment]
> I can change it so that it also forwards HUB_STOP and DEV_STOP along with an alarm armed event.

I'm sorry, I don't follow you.

**Important information:**

The P2P connection is not maintained on all devices, so you have to resort to push notifications (e.g. on battery-operated devices without HB). Therefore, I would implement both.

**Comment by Palmke** [comment]
I may have an alternative for the alarm armed event which involves parameters `ARM_DELAY_HOME` till `ARM_DELAY_CUS3`.
They have JSON data that contain the security mode and alarm configuration:
```
{
    "account_id": "xxxxxxxxxxxxxxxxxxxxxx",
    "count_down_alarm": {
        "channel_list": [
            32,
            (...)
        ],
        "delay_time": 30
    },
    "count_down_arm": {
        "channel_list": [
            16,
            (...)
        ],
        "delay_time": 15
    },
    "devices": [
        {
            "action": 9,
            "device_channel": 0
        }
        (...)
     }
    "mode_id": 0
}
```

It maps what action each device takes when in that mode. `count_down_alarm` is alarm delay and contains the devices that trigger the alarm but adhere to the leave delay (you can also select devices that trigger the alarm without delay).
`count_down_arm` is the leave delay and lastly `mode_id` specifies which mode this configuration is for.
I don't know the mapping for `action` and `device_channel` corresponds to a device connected to the station (which can be found in the device's list of the station's hub data (_get_hub_data_).

Also, for mode 6 (aka OFF), the parameter containing the mode configuration as above is `1180`. This one is missing from the `ParamType` enums in both http/p2p `types.ts`.

**Comment by Palmke** [comment]
Woah, what happened? Now there will potentially be two events generated. One from p2p and one from push data.

**Comment by bropat** [comment]
I leave the decision to you, as I don't use these features ;)

**Comment by Palmke** [comment]
I will add an exclusion for HB2 device type when receiving an alarm push notification from it

**Pull request merged**
