### PR TITLE
FIX: prevent critical error. Causing crash on Homey platform

### PR DESCRIPTION
**Pull request by martijnpoppen**

### CODE REVIEW

**Comment by bropat** [comment]
@martijnpoppen

Do you have an example of a value that causes the error? Perhaps a null-terminated string arrives?

**Comment by martijnpoppen** [comment]
```
EufyLibrary] Invalid Property personDetected error InvalidPropertyError: Property personDetected invalid at Camera.getPropertyMetadata (/node_modules/eufy-security-client/build/http/device.js:608:15) at Camera.updateProperty (/node_modules/eufy-security-client/build/http/device.js:62:48) at Camera.processPushNotification (/node_modules/eufy-security-client/build/http/device.js:1438:30) at /node_modules/eufy-security-client/build/eufysecurity.js:914:32 at Array.forEach (<anonymous>) at /node_modules/eufy-security-client/build/eufysecurity.js:912:25 at processTicksAndRejections (node:internal/process/task_queues:96:5) [EufyLibrary] Invalid Property personDetected error InvalidPropertyError: Property personDetected invalid at Camera.getPropertyMetadata (/node_modules/eufy-security-client/build/http/device.js:608:15) at Camera.updateProperty (/node_modules/eufy-security-client/build/http/device.js:62:48) at Timeout._onTimeout (/node_modules/eufy-security-client/build/http/device.js:1442:34) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7) [EufyLibrary] Invalid Property personDetected error InvalidPropertyError: Property personDetected invalid at Camera.getPropertyMetadata (/node_modules/eufy-security-client/build/http/device.js:608:15) at Camera.updateProperty (/node_modules/eufy-security-client/build/http/device.js:62:48) at Camera.processPushNotification (/node_modules/eufy-security-client/build/http/device.js:1438:30) at /node_modules/eufy-security-client/build/eufysecurity.js:914:32 at Array.forEach (<anonymous>) at /node_modules/eufy-security-client/build/eufysecurity.js:912:25 at processTicksAndRejections (node:internal/process/task_queues:96:5) [EufyLibrary] Invalid Property personDetected error InvalidPropertyError: Property personDetected invalid at Camera.getPropertyMetadata (/node_modules/eufy-security-client/build/http/device.js:608:15) at Camera.updateProperty (/node_modules/eufy-security-client/build/http/device.js:62:48) at Timeout._onTimeout (/node_modules/eufy-security-client/build/http/device.js:1442:34) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7) [EufyLibrary] Invalid Property personDetected error InvalidPropertyError: Property personDetected invalid at Camera.getPropertyMetadata (/node_modules/eufy-security-client/build/http/device.js:608:15) at Camera.updateProperty (/node_modules/eufy-security-client/build/http/device.js:62:48) at Camera.processPushNotification (/node_modules/eufy-security-client/build/http/device.js:1438:30) at /node_modules/eufy-security-client/build/eufysecurity.js:914:32 at Array.forEach (<anonymous>) at /node_modules/eufy-security-client/build/eufysecurity.js:912:25 at processTicksAndRejections (node:internal/process/task_queues:96:5) [EufyLibrary] Invalid Property personDetected error InvalidPropertyError: Property personDetected invalid at Camera.getPropertyMetadata (/node_modules/eufy-security-client/build/http/device.js:608:15) at Camera.updateProperty (/node_modules/eufy-security-client/build/http/device.js:62:48) at Timeout._onTimeout (/node_modules/eufy-security-client/build/http/device.js:1442:34) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7) [EufyLibrary] Invalid Property personDetected error InvalidPropertyError: Property personDetected invalid at Camera.getPropertyMetadata (/node_modules/eufy-security-client/build/http/device.js:608:15) at Camera.updateProperty (/node_modules/eufy-security-client/build/http/device.js:62:48) at Camera.processPushNotification (/node_modules/eufy-security-client/build/http/device.js:1438:30) at /node_modules/eufy-security-client/build/eufysecurity.js:914:32 at Array.forEach (<anonymous>) at /node_modules/eufy-security-client/build/eufysecurity.js:912:25 at processTicksAndRejections (node:internal/process/task_queues:96:5) undefined:1 {"a":1,"s":"T8111H2218390D7C","c":0,"i":"0","k":168,"create_time":1675773446852,"session_id":"20230207_133726","notification_style":2,"push_count":1,"pic_url":"https://security-app-eu.eufylife.com/v1/s/g/s5JvyCrqN","p":"20230207133724","n":"kitchen SyntaxError: Unexpected token in JSON at position 248 at JSON.parse (<anonymous>) at /node_modules/eufy-security-client/build/push/client.js:232:38 at Array.forEach (<anonymous>) at PushClient.convertPayloadMessage (/node_modules/eufy-security-client/build/push/client.js:230:17) at PushClient.handleParsedMessage (/node_modules/eufy-security-client/build/push/client.js:179:43) at PushClientParser.<anonymous> (/node_modules/eufy-security-client/build/push/client.js:79:63) at PushClientParser.emit (node:events:526:28) at PushClientParser.onGotMessageBytes (/node_modules/eufy-security-client/build/push/parser.js:160:14) at PushClientParser.handleFullMessage (/node_modules/eufy-security-client/build/push/parser.js:89:22) at PushClientParser.waitForData (/node_modules/eufy-security-client/build/push/parser.js:74:18)
```

**Comment by bropat** [comment]
@martijnpoppen 

The error above does not show the entire push notification, so I cannot say exactly where the cause is.
In other cases, the problem was a null-terminated string. I have now implemented a solution for this.
Can you try if you still get the same error in version '2.4.1'?

**Comment by martijnpoppen** [comment]
Thanks @bropat 
I'm going to give it a try.
Can't say yet if it works as I only receive crash reports when it doesn't :p

**Comment by martijnpoppen** [comment]
@bropat yes looks good! Thanks :D

**Pull request closed without merging**
