### PR TITLE
NEW: Add Doorbell E340 (T8214)

### PR DESCRIPTION
**Pull request by martijnpoppen**
Hi @bropat 
Support for the new dual Doorbell.

I tested most features except streaming

Doorbell can be added as standalone device or connected to the new minibase chime / Homebase 2 / Homebase 3

I can share the device with you

### CODE REVIEW

**Comment by bropat** [comment]
Todo:

- [ ] Add entry for device in docs/supported_devices.md
- [ ] Add images for device under docs/_media
- [ ] Test streaming

**Comment by bropat** [comment]
@martijnpoppen 

Can you please share the device with me?

* patrick.broetto+eu1@gmail.com

**Comment by martijnpoppen** [comment]
@bropat do you have a US account? I have my devices in US

**Comment by bropat** [comment]
@martijnpoppen 

yes, see above ;)

**Comment by martijnpoppen** [comment]
Oh wow haha
Yes will share in a bit!

**Comment by martijnpoppen** [comment]
@bropat shared. Also the S340.

The E340 is connnected to a Homebase 2. (so I had to share 2 other devices aswell(

**Comment by bropat** [comment]
@martijnpoppen 

Thanks!

FYI: You have shared them on the EU1 account :D

Lunch break ;)

I will contact you as soon as I no longer need the access.

**Comment by martijnpoppen** [comment]
copied it from email but you edited the post. Its definitely weekend.. 😅

**Comment by bropat** [comment]
> copied it from email but you edited the post. Its definitely weekend.. 😅

You have also shared the wrong device (S340)😅
I will now integrate this device for the time being.

**Comment by martijnpoppen** [comment]
@bropat as mentioned:

I shared the E340 and S340

E340 is called Deurbel and is added to the Homebase 2

**Comment by bropat** [comment]
@martijnpoppen 

The S340 camera is no longer accessible (seems offline). Can you check?

**Comment by martijnpoppen** [comment]
@bropat thats exactly what i meant in the PR of the S340. 

Will check when im home

**Comment by bropat** [comment]
@martijnpoppen 

Ok, thanks. But it is also offline from the perspective of the Eufy app, so I'm guessing a firmware problem... ;)

Let me know how you solve the problem (e.g. reboot the camera or similar).

**Comment by martijnpoppen** [comment]
@bropat thats exactly what i meant in the PR of the S340. 

Will check when im home

**Comment by bropat** [comment]
Livestreaming for the Doorbell E340 (T8214) device works.

**TODO**

- [ ] Fix properties for the Doorbell E340 (T8214) device

**Comment by martijnpoppen** [comment]
@bropat S340 is online again.

> Let me know how you solve the problem (e.g. reboot the camera or similar).

I waved  (👋🏼 ) at the camera and it's back

**Comment by brianallen14** [comment]
I have an E340 (T8214) as well if you need additional access.

**Pull request merged**
