### PR TITLE
Fix push notification issue on new indoor outdoor camera device

### PR DESCRIPTION
**Pull request by lenoxys**
### Fixed
 - Fix push notification issue on new device type (INDOOR_OUTDOOR_CAMERA_1080P, INDOOR_OUTDOOR_CAMERA_1080P_NO_LIGHT, INDOOR_OUTDOOR_CAMERA_2K)
 - Typo fix comma instead of semicolon

### CODE REVIEW

**Comment by lenoxys** [comment]
I've someone on the plugin who raised the issue I was able to reproduce it on my lab. Waiting is feedback if he is using the same INDOOR device or SOLO one. If it's SOLO one we might need to add them as well.

    Raw push message received {
      id: '5F8C*******',
      from: '348804314802',
      to: 'eHGi2BdnGOIxyPDNvMdqCK',
      category: 'com.oceanwing.battery.cam',
      persistentId: '0:1629385088939439%0d2a775cf9fd7ecd',
      ttl: 3600,
      sent: '1629385088936',
      payload: {
        device_sn: '',
        payload: {
          msg_type: 18,
          event_type: 3102,
          device_sn: 'T8442P************',
          name: 'Garage',
          channel: 0,
          cipher: 48,
          session_id: '20210819_16****',
          pic_url: 'https://security-app-eu.eufylife.com/v1/s/g/************',
          create_time: 1629385087859,
          trigger_time: 1629385087839,
          file_path: '/media/mmcblk0p1/Camera00/20210819********.dat',
          push_count: 1,
          notification_style: 3,
          storage_type: 3,
          unique_id: 'e6f8783df21258f37*************9b5e4'
        },
        station_sn: 'T8442P************',',
        'google.c.sender.id': '348804******',
        title: 'Outdoor Cam',
        type: '46',
        push_time: '1629385088927',
        content: 'Someone has been spotted',
        event_time: '1629385087859'
      }
    }

**Comment by lenoxys** [comment]
Got the confirmation. Same device than me.

**Comment by bropat** [comment]
@lenoxys Could you please do the pull requests for the `develop` branch.

Thanks!

**Review by bropat — APPROVED** [review]
Good work. Thank you.

**Pull request merged**
