### PR TITLE
feat(smartdrop): adding Smart Drop S300 (T8790)

### PR DESCRIPTION
**Pull request by bassrock**
## Goal

Adds in support for the Smart Drop S300 (T8790). I was able to set this up and use it within HomeAssistant with these properties.

I combined properties from the Safes and Cameras, and they seem to work. If there is a way to dump the exact properties let me know and I can do that isntead.

### CODE REVIEW

**Comment by bassrock** [comment]
Should Resolve #261

**Review by bropat — CHANGES_REQUESTED** [review]
* Missing entry for device in docs/supported_devices.md
* Missing images for device under docs/_media
* Do all changeable properties work correctly?
* Do all executable commands for device and station work (start livestream, reboot station etc.)?

**Comment by flyespresso** [comment]
@bropat @bassrock Anything I can do to help? Happy to test–just got my SmartDrop setup at the new place so awesome to see this PR waiting to get merged :)

**Review by bropat — APPROVED** [review]

**Comment by bropat** [comment]
Todo:

- [ ] Test push notifications
- [ ] Test open SmartDrop p2p command
- [ ] Understand how the delivery pin creation works

**Comment by Williamysays** [comment]
> Todo:
> 
> * [ ]  Test push notifications
> * [ ]  Test open SmartDrop p2p command
> * [ ]  Understand how the delivery pin creation works

Please feel free to use my smartdrop as needed, all can be reset if needed and I will be home to close / change anything as needed for testing.
Appreciate all the hard work as always!

**Comment by bropat** [comment]
@Williamysays 

Can you please close the smart drop?

Thanks :)

**Comment by Williamysays** [comment]
Sorry forgot to reply! / closed!

**Comment by bassrock** [comment]
@bropat sorry i didnt get back, let me know how i can help move this forward.

**Pull request merged**
