### PR TITLE
FIX: set NotificationSwitchModeAPP value

### PR DESCRIPTION
**Pull request by martijnpoppen**
Seems like the value for the APP is 144 instead of 16

### CODE REVIEW

**Comment by martijnpoppen** [comment]
Actually setting it to 144 doesn't work.

The NotificationSwitchModeApp doesnt work on my Homebase.

But when I send it like this it does

```
await this.p2pSession.sendCommandWithStringPayload({
                commandType: CommandType.CMD_SET_PAYLOAD,
                value: JSON.stringify({
                    "account_id": this.rawStation.member.admin_user_id,
                    "cmd": CommandType.CMD_HUB_NOTIFY_MODE,
                    "mValue3": 0,
                    "payload": {
                        "arm_push_mode": 144,
                        "notify_alarm_delay": 1,
                        "notify_mode": 0,
                    }
                }),
                channel: Station.CHANNEL
            }, {
                property: propertyData
            });
```


Any ideas @bropat 

The NotificationSwitchModeKeypad does work

**Comment by bropat** [comment]
@martijnpoppen 

The raw value of this setting hides all possible settings (app, geofence, etc.).

Example: [Look here](https://www.typescriptlang.org/play?#code/MYewdgziA2CmB00QHMAUAiAggBWwLgAJ0AaA1ARgBZKCAyA8gNgEoCBeNhlgbgChRIMBEjToA4gFEA8gDEJAOQDCEwiTJUa9AMwAmVhwK7mfAVDiIUGAMqKAEhIAiAVQAyKoqQrU6BRpX2cfsb84GbClugA0hIAmtiYDqqeGj7kOgAcAQwZxkA)

**Comment by bropat** [comment]
One more thing:

For the properties I would use the high level functions and not the low level.

In your example I would use the method `setStationProperty` of class `EufySecurity`:

```typescript
EufySecurityInstance.setStationProperty(PropertyName.StationNotificationSwitchModeApp, true);
```

**Comment by martijnpoppen** [comment]
Thanks

Strange because i use the station property variant
See https://github.com/martijnpoppen/com.eufylife.security/blob/main/lib/helpers/eufy-events.helper.js#L83


But that doesn't activate the APP notifications

**Pull request closed without merging**
