### PR TITLE
Add support for T8506 (C220) wifi door lock with keypad

### PR DESCRIPTION
**Pull request by justinlindh**
This PR adds support for the T8506 (C220) door lock with wifi and keypad. This is my first contribution to this repository, so please let me know if I missed anything (are there tests in this repo?) and I'll be happy to update.

Tested locally using client/server ws wrapper. Device properties:
```
{
  type: 'result',
  success: true,
  messageId: 'get_properties',
  result: {
    serialNumber: 'T8506<redacted>',
    properties: {
      name: 'Front Door',
      model: 'T8506',
      serialNumber: 'T8506<redacted>',
      hardwareVersion: 'V2',
      softwareVersion: '1.1.1.6',
      type: 184,
      stationSerialNumber: 'T8506<redacted>',
      battery: 100,
      lockStatus: 4,
      autoLock: true,
      autoLockTimer: 60,
      autoLockSchedule: false,
      autoLockScheduleStartTime: '23:00',
      autoLockScheduleEndTime: '6:00',
      wrongTryAttempts: 6,
      wrongTryLockdownTime: 300,
      sound: 2
    }
  }
}
```

Addresses https://github.com/bropat/eufy-security-client/issues/356

### CODE REVIEW

**Comment by justinlindh** [comment]
OK; resolved the failed push notification updates. It's not registering the `lock` command, though; neither through the `device.lock` command or `device.set_property <sn> lock true`, so I'll figure that out.

**Comment by justinlindh** [comment]
I haven't had much time to really drill into this, but in case anybody is interested, I'm blocked on figuring out the Eufy public key request/response at the moment. The API returns (converted to hex, trailing bytes truncated) this: 

```
bfef 22bd bfef efbd bdbf ef28 bdbf ef54 bdbf ef49 bdbf bfef ...
```

This fails in both `getAdvancedLockKey` and `getLockV12P2PCommand` with `Error [ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY]: Public key is not valid for specified curve`

I'll keep playing with this as time allows, but if anybody has any clues on , please let me know.

**Comment by kebel87** [comment]
Did you end up finding a fix? I have the same issue 😔

**Comment by justinlindh** [comment]
Apologies, but I haven't had time to look into it further. I'll try to take a look this week and see if I can get anything further figured out.

**Pull request merged**
