### PR TITLE
Fix issue #196

### PR DESCRIPTION
**Pull request by Palmke**

### CODE REVIEW

**Comment by bropat** [comment]
@Palmke 

I have implemented the fix and changed some parts according to the lib standards. Could you please try version 2.2.0-rc.1 and let me know if everything works correctly?

Thanks!

**Comment by Palmke** [comment]
Will do when I have some spare time.

**Comment by Palmke** [comment]
Running it now... will report back if there any errors :)

**Comment by bropat** [comment]
Can you give me more details?
I tried it myself and I already get for example the following event: `alarm arm delay event`.

**Comment by Palmke** [comment]
Didn't know you had a Homebase 2 ;) 
I have to look into this in more detail, if you say it's working fine it, then it might be an issue in the schema version I use for the websocket or something.
I don't have a lot of time right now so if this is the only PR/issue holding you back, don't wait for me to release a new version.

I know where to find the PR button again if I can't get it to work :)

**Pull request closed without merging**
