### PR TITLE
FIX: HB3 Doorbell Known Face detection not coming trough and Doorbell Ringing

### PR DESCRIPTION
**Pull request by martijnpoppen**

### CODE REVIEW

**Comment by GijsvanDulmen** [comment]
@martijnpoppen Does this still work? Are you using T8214 doorbell by any chance? I wanted to make the face detection to work for this type of doorbell as well cause I do see the information being there. Just not mapped.

**Comment by martijnpoppen** [comment]
Yes this works but is not merged yet. So for my integration its working

**Comment by martijnpoppen** [comment]
@GijsvanDulmen you can always check my up-to-date branch were i updated this already: https://github.com/martijnpoppen/eufy-security-client/tree/homey-integration

**Comment by GijsvanDulmen** [comment]
@martijnpoppen Thanks. Got it working in eufy-security-ws. It fixes my HB3 missing face detection!

**Pull request merged**
